version: '{build}'
image: Visual Studio 2019

environment:
    matrix:
        - job_name: Java 8, python 3.8
          JAVA_HOME: C:\Program Files\Java\jdk1.8.0
          PYTHON: "C:\\Python38-x64"
          PIP: 22.0.4
        - job_name: Java 11, python 3.8
          JAVA_HOME: C:\Program Files\Java\jdk11
          PYTHON: "C:\\Python38-x64"
          PIP: 22.0.4
        - job_name: Java 11, python 3.10
          JAVA_HOME: C:\Program Files\Java\jdk11
          PYTHON: "C:\\Python310-x64"
          PIP: 22.0.4

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - python -m pip install -U pip==%PIP%
  - python -m pip --version
  - python -m pip install -U virtualenv==20.4.2
  - python -m pip install codecov --user

build_script:
  - ./gradlew assemble --no-daemon
test_script:
  - ./gradlew check --no-daemon

on_success:
  - ./gradlew jacocoTestReport --no-daemon
  - python -m codecov -f build\reports\jacoco\test\jacocoTestReport.xml -F windows

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper