version: '{build}'

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
          PYTHON: "C:\\Python34-x64"

install:
  - ps: choco install python
  - python --version
  - pip --version

build_script:
  - ./gradlew assemble --no-daemon
test_script:
  - ./gradlew check --no-daemon

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper